#!/bin/sh
chown -R tomcat7:tomcat7 /var/cache/oxgarage
perl -p -i -e "s/localhost/`hostname -f`/" /var/lib/tomcat7/webapps/ege-webclient/WEB-INF/web.xml

if which invoke-rc.d >/dev/null 2>&1; then
  test -f  /etc/init.d/tomcat7 && invoke-rc.d tomcat7 restart
else
  test -f  /etc/init.d/tomcat7 && /etc/init.d/tomcat7 restart
fi


